language: go

matrix:
  fast_finish: true
  include:
    - go: 1.13.x
      env:
        - TESTTAGS=nomsgpack
        - GO111MODULE=on
    - go: 1.14.x
      env:
        - TESTTAGS=nomsgpack
        - GO111MODULE=on


branches:
  only:
    - master

git:
  depth: 10

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
  - if [ ! -f "$(pwd)/.travis/build.sh" ]; then chmod +x $(pwd)/.travis/build.sh ; fi
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/movie-system.enc -out ~/.ssh/id_rsa_github -d
  - chmod 600 ~/.ssh/id_rsa_github
  - mv -fv .travis/ssh_config ~/.ssh/config
  - git config --global user.name "Tak via travis-cli"
  - git config --global user.email "br7roy@gmail.com"

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
#  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

#go_import_path: github.com/gin-gonic/gin

script:
  - go test -v $(pwd)
#  - make vet
#  - make fmt-check
#  - make misspell-check
#  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/7f95bf605c4d356372f4
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false


after_success:
  - echo `pwd` && ls && bash .travis/build.sh
