application: movie_system 
version: 1
runtime: go113
api_version: go1

handlers:
- url: /.*
  script: _go_app

server:
  mode: debug
  host: 0.0.0.0
  port: 8080

database:
  type: mysql
  storeHouse: movie-system
  url: 127.0.0.1
  password:

jwt:
  secret: asdjfoiwaef
  expired: 100000

#https://blog.csdn.net/hexiaoyun128/article/details/83109598