application: movie_system 
version: 1
runtime: go113
api_version: go1

handlers:
- url: /.*
  script: _go_app

server:
  mode: debug
  port: 8080

database:
  type: mysql
  storeHouse: movie-system
  port: 3306
  url: 172.17.0.2
  userName: movie-system
  password: ZaW6rjRcee26ijEc

jwt:
  secret: asdjfoiwaef
  expired: 100000
